import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Bot, Braces, Check, Code2, Languages, Lightbulb, LockKeyhole, ShieldCheck, Sparkles, UserRoundCheck, X } from "lucide-react";
import { Logo } from "@/components/brand/logo";
import { ButtonLink } from "@/components/ui/button";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "How KAKI uses AI",
  description: "A transparent view of where OpenAI and Codex are used in KAKI—and where human judgement remains in control.",
};

export default function AiUsePage() {
  const configured = Boolean(process.env.OPENAI_API_KEY);
  const model = process.env.OPENAI_MODEL || "gpt-5-mini";

  return <main className="min-h-screen"><header className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8"><Logo /><div className="flex items-center gap-3"><Link href="/share" className="hidden text-sm font-black text-muted hover:text-purple sm:block">Share QR</Link><ButtonLink href="/ask" className="min-h-11 px-4">Try AI live <ArrowRight className="size-4" /></ButtonLink></div></header><section className="mx-auto max-w-7xl px-5 pb-24 pt-7 sm:px-8"><div className="grain relative overflow-hidden rounded-[42px] bg-purple p-8 text-white shadow-[0_28px_80px_rgba(109,85,217,.23)] sm:p-12"><div className="relative z-10 max-w-4xl"><div className="inline-flex items-center gap-2 rounded-full bg-white/10 px-4 py-2 text-xs font-black uppercase tracking-[.15em] text-sun"><Bot className="size-4" />AI with a clear job</div><h1 className="mt-6 text-balance text-5xl font-black leading-[.94] tracking-[-.065em] sm:text-7xl">AI organises.<br /><span className="text-sun">Neighbours decide.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/72">KAKI uses AI to reduce the friction between “I need a little help” and a safe, understandable community mission. It never replaces consent, human judgement or organiser review.</p><div className="mt-7 flex flex-wrap gap-3"><span className={`rounded-full px-4 py-2 text-xs font-black ${configured ? "bg-mint text-[#17654d]" : "bg-coral text-white"}`}>{configured ? "● OpenAI key configured" : "○ OpenAI key not detected"}</span><span className="rounded-full bg-white/10 px-4 py-2 text-xs font-black">Mission model: {model} · Suggestions: {process.env.OPENAI_SUGGESTIONS_MODEL || "gpt-4.1-nano"}</span><span className="rounded-full bg-white/10 px-4 py-2 text-xs font-black">Structured Outputs + Zod</span></div></div><Sparkles className="absolute right-[8%] top-[22%] hidden size-40 rotate-12 text-white/10 lg:block" /></div>

      <section className="mt-16"><p className="text-xs font-black uppercase tracking-[.18em] text-purple">Runtime AI journey</p><h2 className="mt-3 max-w-3xl text-balance text-4xl font-black tracking-[-.055em] sm:text-5xl">From an unfinished thought to a safe mission.</h2><div className="mt-8 grid gap-4 lg:grid-cols-5"><FlowStep number="01" icon={<Lightbulb />} title="Live suggestions" text="As a resident types, OpenAI proposes three relevant, tappable ways to complete the request." /><FlowStep number="02" icon={<Languages />} title="Voice & translation" text="OpenAI transcribes recordings and translates requests or chat messages. Originals remain available for review." /><FlowStep number="03" icon={<Braces />} title="Structured mission" text="OpenAI returns title, category, summary, duration, location and a practical guide in a strict schema." /><FlowStep number="04" icon={<ShieldCheck />} title="Safety triage" text="Sensitive or unsafe needs are marked for organiser review instead of community matching." /><FlowStep number="05" icon={<UserRoundCheck />} title="Human approval" text="The resident reviews the result before publishing; neighbours choose whether to participate." /></div></section>

      <section className="mt-16 grid gap-6 lg:grid-cols-2"><div className="paper-card rounded-[36px] p-7 sm:p-9"><div className="flex items-center gap-3"><span className="grid size-12 place-items-center rounded-2xl bg-mint text-[#17654d]"><Check className="size-6" /></span><h2 className="text-3xl font-black tracking-[-.05em]">What AI does</h2></div><ul className="mt-7 space-y-4"><Point text="Explains a human-chosen pairing using self-reported language and skills; unknowns stay explicit" /><Point text="Transcribes short microphone recordings with OpenAI; the transcript stays editable" /><Point text="Translates requests and chat messages into English, Chinese, Malay or Tamil on demand" /><Point text="Suggests a friendly icebreaker for the two participants" /><Point text="Suggests clearer community requests from partial text" /><Point text="Classifies requests into digital, wellbeing, repair, food or skills" /><Point text="Turns free-form language into a short, actionable mission" /><Point text="Produces a three-to-five-step helper guide" /><Point text="Flags crisis, medical, financial, private-home and unsafe repair needs" /></ul></div><div className="rounded-[36px] bg-ink p-7 text-white sm:p-9"><div className="flex items-center gap-3"><span className="grid size-12 place-items-center rounded-2xl bg-white/10 text-coral"><X className="size-6" /></span><h2 className="text-3xl font-black tracking-[-.05em]">What AI does not do</h2></div><ul className="mt-7 space-y-4 text-white/70"><DarkPoint text="It does not diagnose, counsel or respond to emergencies" /><DarkPoint text="It does not expose private addresses or personal account data" /><DarkPoint text="It does not autonomously assign a neighbour" /><DarkPoint text="It does not publish a mission without the resident’s confirmation" /><DarkPoint text="It does not replace the community organiser’s safety judgement" /></ul></div></section>

      <section className="mt-16 grid overflow-hidden rounded-[40px] border border-ink/10 bg-white/65 lg:grid-cols-[.8fr_1.2fr]"><div className="bg-sun/35 p-8 sm:p-10"><Code2 className="size-12 text-purple" /><p className="mt-6 text-xs font-black uppercase tracking-[.16em] text-purple">Build-time AI</p><h2 className="mt-3 text-4xl font-black tracking-[-.055em]">Built end-to-end with Codex.</h2><p className="mt-4 leading-7 text-muted">Codex helped scaffold, design, implement and verify the Next.js PWA, Supabase schema, RLS policies, realtime flows, visual assets and tests. This is development assistance—not a hidden runtime decision-maker.</p></div><div className="p-8 sm:p-10"><div className="flex items-start gap-3 rounded-2xl bg-mint/55 p-4 text-sm leading-6 text-[#17654d]"><LockKeyhole className="mt-0.5 size-5 shrink-0" /><p><strong className="block">Privacy boundary</strong>The OpenAI key stays on the server. AI endpoints require a valid session, including a temporary guest session during the event, and enforce shared database-backed usage limits. Match introductions send the request and self-reported language/skills, not account identifiers. Voice recordings are sent to OpenAI for transcription, not to a browser speech service; KAKI does not persist the audio. Translation sends only the selected text and target language.</p></div><div className="mt-5 flex items-start gap-3 rounded-2xl bg-purple/7 p-4 text-sm leading-6 text-purple-dark"><ShieldCheck className="mt-0.5 size-5 shrink-0" /><p><strong className="block">Graceful fallback</strong>If a model call fails, we show an honest error and keep the request editable. When no API key is configured, mission drafts use labelled deterministic rules. Suggestions and match explanations are never faked. The journey scene is decorative animation, not AI or GPS tracking.</p></div><div className="mt-7 flex flex-wrap gap-3"><ButtonLink href="/ask">Try the AI flow <Sparkles className="size-4" /></ButtonLink><ButtonLink href="/share" variant="secondary">Open share QR</ButtonLink></div></div></section>
    </section></main>;
}

function FlowStep({ number, icon, title, text }: { number: string; icon: React.ReactNode; title: string; text: string }) {
  return <article className="paper-card rounded-[28px] p-5"><div className="flex items-center justify-between"><span className="grid size-11 place-items-center rounded-2xl bg-purple text-white">{icon}</span><span className="text-3xl font-black text-ink/10">{number}</span></div><h3 className="mt-5 text-lg font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-muted">{text}</p></article>;
}

function Point({ text }: { text: string }) { return <li className="flex items-start gap-3 text-sm leading-6 text-muted"><span className="mt-0.5 grid size-6 shrink-0 place-items-center rounded-full bg-mint text-[#17654d]"><Check className="size-3.5" /></span>{text}</li>; }
function DarkPoint({ text }: { text: string }) { return <li className="flex items-start gap-3 text-sm leading-6"><span className="mt-0.5 grid size-6 shrink-0 place-items-center rounded-full bg-white/8 text-coral"><X className="size-3.5" /></span>{text}</li>; }
