"use client";
import { useState } from "react";
import { Check, MessageCircle, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { MatchInsight } from "@/lib/ai/match-schema";

export function MatchReveal({ missionId, onIcebreaker }: { missionId: string; onIcebreaker: (text: string) => void }) {
  const [insight, setInsight] = useState<MatchInsight | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  async function reveal() {
    setBusy(true); setError("");
    try {
      const response = await fetch(`/api/missions/${missionId}/match`, { method: "POST" });
      const payload = await response.json();
      if (!response.ok) throw new Error(payload.error);
      setInsight(payload.insight);
    } catch (error) { setError(error instanceof Error ? error.message : "Please try again."); }
    finally { setBusy(false); }
  }
  return <section className="relative overflow-hidden rounded-2xl bg-purple p-4 text-white sm:p-8">
    <Sparkles className="absolute -right-6 -top-6 size-36 rotate-12 text-white/5" />
    <p className="text-xs font-black uppercase tracking-[.18em] text-sun">A little AI. A human connection.</p>
    <h2 className="mt-3 text-3xl font-black tracking-tight">{insight?.headline || "What could you share?"}</h2>
    <p className="mt-3 leading-7 text-white/75">{insight?.summary || "Your neighbour chose to help. Let KAKI turn the details you’ve shared into a friendly introduction."}</p>
    {insight ? <div className="mt-6 space-y-3">{insight.reasons.map((reason, index) => <div key={`${reason.label}-${index}`} className="reveal-in rounded-2xl bg-white/10 p-4" style={{ animationDelay: `${index * 120}ms` }}><p className="flex flex-wrap items-center gap-2 text-sm font-black">{reason.evidence === "shared" ? <Check className="size-4 text-mint" /> : <MessageCircle className="size-4 text-sun" />}{reason.label}<span className="ml-auto text-[10px] font-bold text-white/60">{reason.evidence === "shared" ? "Self-reported" : "Ask each other"}</span></p><p className="mt-2 text-sm leading-6 text-white/75">{reason.detail}</p></div>)}<button onClick={() => onIcebreaker(insight.icebreaker)} className="mt-3 w-full rounded-2xl border border-white/25 p-4 text-left text-sm leading-6 hover:bg-white/10"><span className="block font-black text-sun">Tap to put this icebreaker in chat</span>{insight.icebreaker}</button></div> : <Button variant="secondary" disabled={busy} className="mt-5 w-full bg-white text-purple sm:w-auto" onClick={() => void reveal()}><Sparkles className={`size-4 ${busy ? "animate-pulse" : ""}`} />{busy ? "Finding common ground…" : "Reveal our connection"}</Button>}
    {error ? <p role="alert" className="mt-4 text-sm text-sun">{error}</p> : null}
    <p className="mt-5 text-[11px] text-white/60">{insight ? "Generated by OpenAI · " : ""}Not a compatibility score or a verification check. You decide together.</p>
  </section>;
}
